### PR TITLE
add validation tests

### PR DESCRIPTION
**Pull request by zoedberg**
This PR introduces some consignment validation tests.

I propose to rename this repo from rgb-integration-tests to rgb-tests since the added tests are not integration and also because I plan to add some stress tests to this repo. 

@dr-orlovsky please let me know if you agree with the tests and the rename, if so before merging this let me fix the README

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
I agree and fine with the rename

**Comment by zoedberg** [comment]
@dr-orlovsky done, this can be merged. Please also change the name of the repo, I don't have the permissions to do so

**Comment by dr-orlovsky** [comment]
Thank you. Re-named. Strange that you can't rename the repo: you are maintainer here...

**Review by dr-orlovsky — APPROVED** [review]
ACK b0c367a8fe4c606341e29c03d3d7723e622eb0e1

**Pull request merged**
